# Generated by Django 5.1.2 on 2024-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='balance',
        ),
        migrations.AlterField(
            model_name='award',
            name='gets_scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
